version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Building the project"

  call-endpoint:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Call the Endpoint
          command: |
            curl -X POST "https://dummyjson.com/todos"
            echo "Endpoint called."

  skip-endpoint:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Skipping the Endpoint Call
          command: |
            echo "User chose to skip calling the endpoint."

workflows:
  version: 2
  run-build:
    jobs:
      - build
      - hold:
          type: approval
      - call-endpoint:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
      - skip-endpoint:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
