version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Building the project"

  call-endpoint:
    docker:
      - image: curlimages/curl:7.87.0
    steps:
      - run:
          name: Call the Endpoint
          command: |
            echo "User chose to call the endpoint."
            curl "https://dummyjson.com/todos"

  skip-endpoint:
    docker:
      - image: alpine:3.18
    steps:
      - run:
          name: Skip the Endpoint Call
          command: |
            echo "User chose to skip calling the endpoint."

  continue-workflow:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Continuing with the next steps in the workflow..."

workflows:
  version: 2
  run-build:
    jobs:
      - build
      - call-approval:
          type: approval
          requires:
            - build
      - skip-approval:
          type: approval
          requires:
            - build
      - call-endpoint:
          requires:
            - call-approval
      - skip-endpoint:
          requires:
            - skip-approval
      - continue-workflow:
          requires:
            - call-endpoint
            - skip-endpoint
