version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Building the project"

  call-endpoint:
    docker:
      - image: curlimages/curl:7.87.0
    steps:
      - run:
          name: Call the Endpoint
          command: |
            echo "User chose to call the endpoint."
            curl -X GET "https://dummyjson.com/todos"

  continue-workflow:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Continuing with the next steps in the workflow..."

workflows:
  version: 2
  run-build:
    jobs:
      - build
      - call-approval:
          type: approval
          name: "Approval Required: API Call Awareness"
          description: |
            Please review before proceeding:
            - This step might need to call an external endpoint.
            - Make sure all prerequisites are met before proceeding.
            - If you're unsure, consult with the team before approving.
          requires:
            - build
      - call-endpoint:
          requires:
            - call-approval
      - continue-workflow:
          requires:
            - call-endpoint
