version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Building the project"

  call-endpoint:
    docker:
      - image: curlimages/curl:7.87.0
    steps:
      - run:
          name: Call the Endpoint
          command: |
            echo "User chose to call the endpoint."
            curl -X GET "https://dummyjson.com/todos"

  deploy-to-prod:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Continuing with the next steps in the workflow..."

workflows:
  version: 2
  run-build:
    jobs:
      - build
      - approve-step:
          type: approval
          requires:
            - build
      - aprove-stop-tasks:
          type: approval
          requires:
            - build
      - call-endpoint:
          requires:
            - aprove-stop-tasks
          filters:
            branches:
              ignore: "*"
      - deploy-to-prod:
          requires:
            - approve-step
