version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Building the project"

  continue-workflow:
    docker:
      - image: alpine:3.18
    steps:
      - run: echo "Continuing with the next steps in the workflow..."

workflows:
  version: 2
  run-build:
    jobs:
      - build
      - approve-step:
          type: approval
          description: |
            Please review the following before proceeding:
            - Ensure all prerequisites are met.
            - Be aware of any external dependencies.
            - Consult with the team if you are unsure about proceeding.
          requires:
            - build
      - continue-workflow:
          requires:
            - approve-step
