version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Building the project"

  call-endpoint:
    docker:
      - image: curlimages/curl:7.87.0
    steps:
      - run:
          name: Call the Endpoint
          command: |
            echo "Calling the endpoint..."
            curl "https://dummyjson.com/todos"

  skip-endpoint:
    docker:
      - image: curlimages/curl:7.87.0
    steps:
      - run:
          name: Skip the Endpoint Call
          command: echo "Skipping the endpoint call as no approval was given."

workflows:
  version: 2
  run-build:
    jobs:
      - build
      - hold-for-approval:
          type: approval
      - call-endpoint:
          requires:
            - hold-for-approval
